service:
  name: user-thrift-service
  port: 7911

#数据源
spring:
  datasource:
    url: jdbc:mysql://47.98.134.237:3306/microsevice_demo
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver