server:
  name: user-edge-service
  port: 8082

thrift:
  user:
    ip: 127.0.0.1
    port: 7911
  message:
    ip: 127.0.0.1
    port: 9090

#redis
spring:
  redis:
    host: 192.168.5.155
    port: 6379
    timeout: 30000